[package]
name = "scil_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Threading",
] }
